### ISSUE TITLE
peer to peer code review

### ISSUE THREAD

**Issue by omar-muhamad** [Omar-Muhamad/Capstone-Project-1#1]

**Comment by youmari** [comment]
# To Highlight :
##  The website looks clean, work as expected and there is no errors or bugs 💯

**Comment by edwardoluyara** [comment]
Your project looks great but I was getting worried when I saw that you used double quotes instead of single quote In your JavaScript strings for some reason it worked for you but never worked for me that's what I taught but I would rather say "great job man"👏👏👏💯
